apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deploment
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: adolfoherrera1417/portfolio-app:1.0
        ports:
        - containerPort: 80